replicaCount: 2

image:
  repository: model-connectors-service
  tag: 2.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  SPRING_PROFILES_ACTIVE: prod
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
