apiVersion: v1
kind: Service
metadata:
  name: model-connectors-service
  namespace: model-box
  labels:
    app.kubernetes.io/name: model-connectors-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app.kubernetes.io/name: model-connectors-service
