-- ==============================================================================
-- MESSAGES AND COMPACTIONS TABLES DDL
-- Table and column names in UPPER CASE adhering to enterprise SQL standards.
-- Compatible with PostgreSQL and In-Memory ANSI SQL (SQLite / H2).
-- ==============================================================================

CREATE TABLE IF NOT EXISTS MB_MESSAGES (
    MESSAGE_ID VARCHAR(64) PRIMARY KEY,
    SESSION_ID VARCHAR(64) NOT NULL REFERENCES MB_SESSIONS(SESSION_ID) ON DELETE CASCADE,
    ROLE VARCHAR(32) NOT NULL,
    CONTENT TEXT NOT NULL,
    TOKEN_COUNT INT NOT NULL DEFAULT 0,
    TIMESTAMP TIMESTAMP NOT NULL,
    MODEL_NAME VARCHAR(128) NOT NULL,
    CONNECTOR_PROTOCOL VARCHAR(32) NOT NULL,
    METADATA_JSON TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS MB_COMPACTIONS (
    COMPACTION_ID VARCHAR(64) PRIMARY KEY,
    SESSION_ID VARCHAR(64) NOT NULL REFERENCES MB_SESSIONS(SESSION_ID) ON DELETE CASCADE,
    SUMMARY_CONTENT TEXT NOT NULL,
    COMPACTED_MESSAGE_IDS_JSON TEXT NOT NULL,
    ORIGINAL_TOKEN_COUNT INT NOT NULL,
    COMPACTED_TOKEN_COUNT INT NOT NULL,
    COMPACTION_RATIO REAL NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_MB_MESSAGES_SESSION_TIME ON MB_MESSAGES (SESSION_ID, TIMESTAMP);
CREATE INDEX IF NOT EXISTS IDX_MB_MESSAGES_PROTOCOL ON MB_MESSAGES (CONNECTOR_PROTOCOL);
CREATE INDEX IF NOT EXISTS IDX_MB_COMPACTIONS_SESSION_TIME ON MB_COMPACTIONS (SESSION_ID, TIMESTAMP);
