-- ==============================================================================
-- CONNECTION CONFIGS TABLE DDL
-- Table and column names in UPPER CASE adhering to enterprise SQL standards.
-- Compatible with PostgreSQL and In-Memory ANSI SQL (SQLite / H2).
-- ==============================================================================

CREATE TABLE IF NOT EXISTS MB_CONNECTION_CONFIGS (
    CONNECTION_ID VARCHAR(64) PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    PROTOCOL VARCHAR(32) NOT NULL,
    ENDPOINT_URL TEXT NOT NULL,
    MODEL_NAME VARCHAR(128) NOT NULL,
    AUTH_METHOD VARCHAR(32) NOT NULL,
    AUTH_PAYLOAD_JSON TEXT NOT NULL DEFAULT '{}',
    TIMEOUT_SECONDS REAL NOT NULL DEFAULT 60.0,
    MAX_RETRIES INT NOT NULL DEFAULT 3,
    RATE_LIMIT_RPM INT NOT NULL DEFAULT 60,
    TOKEN_CAPACITY INT NOT NULL DEFAULT 100000,
    TOKEN_REFILL_RATE_PER_SEC REAL NOT NULL DEFAULT 1000.0,
    STORAGE_BACKEND VARCHAR(32) NOT NULL DEFAULT 'POSTGRESQL'
);

CREATE INDEX IF NOT EXISTS IDX_MB_CONNECTION_CONFIGS_PROTOCOL ON MB_CONNECTION_CONFIGS (PROTOCOL);
CREATE INDEX IF NOT EXISTS IDX_MB_CONNECTION_CONFIGS_MODEL ON MB_CONNECTION_CONFIGS (MODEL_NAME);
