-- ==============================================================================
-- TOKEN CONSUMPTION METRICS TABLE DDL
-- Table and column names in UPPER CASE adhering to enterprise SQL standards.
-- Compatible with PostgreSQL and In-Memory ANSI SQL (SQLite / H2).
-- ==============================================================================

CREATE TABLE IF NOT EXISTS MB_TOKEN_METRICS (
    METRIC_ID VARCHAR(64) PRIMARY KEY,
    SESSION_ID VARCHAR(64) NOT NULL REFERENCES MB_SESSIONS(SESSION_ID) ON DELETE CASCADE,
    CONNECTION_ID VARCHAR(64) NOT NULL,
    TOKENS_CONSUMED INT NOT NULL,
    AVAILABLE_TOKENS INT NOT NULL,
    RECORDED_AT TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_MB_TOKEN_METRICS_SESSION_TIME ON MB_TOKEN_METRICS (SESSION_ID, RECORDED_AT);
CREATE INDEX IF NOT EXISTS IDX_MB_TOKEN_METRICS_CONN_ID ON MB_TOKEN_METRICS (CONNECTION_ID);
