apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-connectors-ingress
  namespace: model-box
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: model-connectors-service
                port:
                  number: 8000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: model-connectors-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: model-connectors-ui
                port:
                  number: 80
