-- ==============================================================================
-- SQLITE MESSAGES AND COMPACTIONS TABLE DDL (In-Memory Engine)
-- Table and column names in UPPER CASE adhering to enterprise SQL standards.
-- ==============================================================================

CREATE TABLE IF NOT EXISTS MB_MESSAGES (
    MESSAGE_ID TEXT PRIMARY KEY,
    SESSION_ID TEXT NOT NULL,
    ROLE TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    TOKEN_COUNT INTEGER NOT NULL DEFAULT 0,
    TIMESTAMP TEXT NOT NULL,
    MODEL_NAME TEXT NOT NULL,
    CONNECTOR_PROTOCOL TEXT NOT NULL,
    METADATA_JSON TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (SESSION_ID) REFERENCES MB_SESSIONS (SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MB_COMPACTIONS (
    COMPACTION_ID TEXT PRIMARY KEY,
    SESSION_ID TEXT NOT NULL,
    SUMMARY_CONTENT TEXT NOT NULL,
    COMPACTED_MESSAGE_IDS_JSON TEXT NOT NULL,
    ORIGINAL_TOKEN_COUNT INTEGER NOT NULL,
    COMPACTED_TOKEN_COUNT INTEGER NOT NULL,
    COMPACTION_RATIO REAL NOT NULL,
    TIMESTAMP TEXT NOT NULL,
    FOREIGN KEY (SESSION_ID) REFERENCES MB_SESSIONS (SESSION_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_MB_MESSAGES_SESSION_TIME ON MB_MESSAGES (SESSION_ID, TIMESTAMP);
CREATE INDEX IF NOT EXISTS IDX_MB_MESSAGES_PROTOCOL ON MB_MESSAGES (CONNECTOR_PROTOCOL);
CREATE INDEX IF NOT EXISTS IDX_MB_COMPACTIONS_SESSION_TIME ON MB_COMPACTIONS (SESSION_ID, TIMESTAMP);
