-- ==============================================================================
-- SQLITE CONNECTION CONFIGS TABLE DDL (In-Memory Engine)
-- Table and column names in UPPER CASE adhering to enterprise SQL standards.
-- ==============================================================================

CREATE TABLE IF NOT EXISTS MB_CONNECTION_CONFIGS (
    CONNECTION_ID TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    PROTOCOL TEXT NOT NULL,
    ENDPOINT_URL TEXT NOT NULL,
    MODEL_NAME TEXT NOT NULL,
    AUTH_METHOD TEXT NOT NULL,
    AUTH_PAYLOAD_JSON TEXT NOT NULL DEFAULT '{}',
    TIMEOUT_SECONDS REAL NOT NULL DEFAULT 60.0,
    MAX_RETRIES INTEGER NOT NULL DEFAULT 3,
    RATE_LIMIT_RPM INTEGER NOT NULL DEFAULT 60,
    TOKEN_CAPACITY INTEGER NOT NULL DEFAULT 100000,
    TOKEN_REFILL_RATE_PER_SEC REAL NOT NULL DEFAULT 1000.0,
    STORAGE_BACKEND TEXT NOT NULL DEFAULT 'IN_MEMORY'
);

CREATE INDEX IF NOT EXISTS IDX_MB_CONNECTION_CONFIGS_PROTOCOL ON MB_CONNECTION_CONFIGS (PROTOCOL);
CREATE INDEX IF NOT EXISTS IDX_MB_CONNECTION_CONFIGS_MODEL ON MB_CONNECTION_CONFIGS (MODEL_NAME);
