-- ==============================================================================
-- SQLITE TOKEN CONSUMPTION METRICS TABLE DDL (In-Memory Engine)
-- Table and column names in UPPER CASE adhering to enterprise SQL standards.
-- ==============================================================================

CREATE TABLE IF NOT EXISTS MB_TOKEN_METRICS (
    METRIC_ID TEXT PRIMARY KEY,
    SESSION_ID TEXT NOT NULL,
    CONNECTION_ID TEXT NOT NULL,
    TOKENS_CONSUMED INTEGER NOT NULL,
    AVAILABLE_TOKENS INTEGER NOT NULL,
    RECORDED_AT TEXT NOT NULL,
    FOREIGN KEY (SESSION_ID) REFERENCES MB_SESSIONS (SESSION_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_MB_TOKEN_METRICS_SESSION_TIME ON MB_TOKEN_METRICS (SESSION_ID, RECORDED_AT);
CREATE INDEX IF NOT EXISTS IDX_MB_TOKEN_METRICS_CONN_ID ON MB_TOKEN_METRICS (CONNECTION_ID);
